---
- name: Install Docker
  become: true
  tags: install
  block:

    - name: Install dependencies
      package:
        name:
          - ca-certificates
          - curl
          - gnupg

    - include_tasks: "add_{{ ansible_distribution }}_apt_repo.yml"

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Ensure Docker is enabled and started
      service:
        name: docker
        enabled: true
        state: started
