---
- name: Install Docker
  become: true
  tags: install
  block:

    - name: Install dependencies
      package:
        name:
          - ca-certificates
          - curl
          - gnupg

    - name: Add APT key
      ansible.builtin.apt_key:
        url: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg'
        state: present

    - name: Add APT repository
      ansible.builtin.apt_repository:
        repo: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
        state: present
      notify: apt update

    - name: Install Docker
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Ensure Docker is enabled and started
      service:
        name: docker
        enabled: true
        state: started
